import type {Metadata} from "next";
import "./globals.css";
import React from "react";
import {Roboto_Condensed} from 'next/font/google';

const robotoCondensed = Roboto_Condensed({
    weight: ["400", "600", "700"],
    style: ["italic", "normal"],
    subsets: ["latin"],
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es">
        <body>
            <main className={robotoCondensed.className}>
                {children}
            </main>
        </body>
        </html>
    );
}
